/**
 * Various functions used in javascript tools
 */
import {
  map,
  clamp,
  norm,
  lerp,
  square,
  degrees,
  radians,
  precision,
} from './modules/maths'
import {
  lerp3,
  intersectCircles,
  intersectLines,
  lerpStops,
  polarToCartesian,
  cartesianToPolar,
  dist,
  dist2,
  distToSegment,
  distToSegment2,
} from './modules/geometry'
import { random, randomDir, randomName, randomIndex } from './modules/random'
import {
  timestampName,
  removeDiacritics,
  removeNonAlphaNumeric,
  splitChunks,
  sepCase,
  snakeCase,
  kebabCase,
  camelCase,
} from './modules/strings'
import {
  copyArray,
  shuffleArray,
  filterUnique,
  fuzzySearch,
  contains,
} from './modules/arrays'
import { lerpColor } from './modules/colors.mjs'
import { getQuarter, quarterExtent, datesBetween } from './modules/dates'
import {
  loadJSON,
  downloadDataUri,
  pageOffset,
  getCSS,
  appendCSS,
  getSVGString,
  svgStringToImage,
  svgToUri,
} from './modules/browser'
import { shallowCopyExcluding } from './modules/objects'
import PID from './modules/pid'
export {
  map,
  clamp,
  random,
  randomDir,
  lerp,
  lerp3,
  lerpStops,
  square,
  dist,
  norm,
  degrees,
  radians,
  intersectCircles,
  intersectLines,
  randomName,
  timestampName,
  randomIndex,
  copyArray,
  shuffleArray,
  filterUnique,
  lerpColor,
  precision,
  loadJSON,
  removeDiacritics,
  removeNonAlphaNumeric,
  splitChunks,
  getQuarter,
  quarterExtent,
  datesBetween,
  downloadDataUri,
  polarToCartesian,
  cartesianToPolar,
  pageOffset,
  fuzzySearch,
  dist2,
  distToSegment,
  distToSegment2,
  sepCase,
  snakeCase,
  kebabCase,
  camelCase,
  contains,
  getCSS,
  appendCSS,
  getSVGString,
  svgStringToImage,
  svgToUri,
  shallowCopyExcluding,
  PID,
}
